theme: jekyll-theme-so-simple
locale: en-US
title: Caio Mizerkowski
description: Eine kleine Nachtblog
baseurl: /
url: 'https://mizerkowski.com.br'
logo: null
date_format: '%B %-d, %Y'
read_time: true
words_per_minute: 200
mathjax:
  enable: true
  combo: null
  tags: null
google_fonts:
  - name: Source Sans Pro
    weights: '400,400i,700,700i'
  - name: Lora
    weights: '400,400i,700,700i'
google_analytics: null
disqus:
  shortname: null
twitter:
  username: null
liquid:
  error_mode: strict
permalink: '/:categories/:title/'
markdown: kramdown
feed:
  path: atom.xml
paginate: 10
paginate_path: '/page:num/'
search_full_content: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      share: true
author:
  name: Caio Mizerkowski
  picture: null
  email: caiomizerkowski@gmail.com
  twitter: null
  links:
    - title: null
      url: null
      icon: null
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
